---
name: Ruby Tests

on:
  pull_request:
  push:
    branches:
      - main
      - '*-stable'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get -qq -y install libcurl4-openssl-dev libxml2-dev
      - name: RuboCop
        uses: theforeman/actions/.github/workflows/rubocop.yml@v0
        with:
          command: bundle exec rubocop --parallel --format github
          ruby: '3.0'

  test:
    name: Ruby
    needs:
      - rubocop
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get -qq -y install libcurl4-openssl-dev libxml2-dev
      - name: Run tests
        uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
        with:
          plugin: foreman_ovirt
