---
name: Test

on:
  pull_request:
  push:
    branches:
      - 'main'
      - '*-stable'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop

  test_ruby:
    name: Ruby
    needs: rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev

      - name: Setup Foreman
        uses: theforeman/actions/setup-foreman-plugin@master
        with:
          plugin: foreman_ovirt

      - name: Run Tests
        run: bundle exec rake test